trigger:
- none

parameters:
- name:  environmentName
  default: 'dev'
  values:
  - dev
  - uat
  - prd
- name: stackName
  default: 'ig'
  values: 
  - ig
  - dev

jobs:
- job: Infrastructure
  displayName: Deploy Infrastructure to ${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: "az-platform-${{ parameters.environmentName }}-WillowPlatform"
      addSpnToEnvironment: true
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $env:ARM_CLIENT_ID=$env:servicePrincipalId
        $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
        $env:ARM_TENANT_ID=$env:tenantId
        $env:ARM_SUBSCRIPTION_ID=$(az account show --query "id" -o tsv)
        $env:AZURE_STORAGE_ACCOUNT='wiluatpltinfraaue1sto'
        $env:AZURE_STORAGE_KEY='+gtifj9NBU3Nivbzq4Hmj6eufYQCIXZWQc9ODyE8k4XOFOFs1tDJ8KYzWT3kH3raCBQp9QeobYjeJvqGP85X0g=='
        $env:PULUMI_CONFIG_PASSPHRASE='test1'
        pulumi login --cloud-url azblob://${{ parameters.environmentName }}
        cd 'infrastructure/deployment/Willow.RealEstate.Deployment'
        pulumi stack select ${{ parameters.environmentName }}
        pulumi preview
        pulumi up --yes
    displayName: 'Environment Variables Setup'

 