secretsprovider: azurekeyvault://platformdevdeploykeys.vault.azure.net/keys/pulumi
encryptedkey: TEtwZ1lmcHhnT0pfZXFPV3hLYnNUekNTRlIycjNCd0R5NHYtNWxLclB3d0ZpV2IzRXRQdXFzTGF4aHBUemRCRTBxZ1VuTGJRRGdwU3JNc1FTLWcyeDZwbDZ3bHJQS0NETEhQOEpsZ3M4TE1aSFZqd1ZPV1dRRXhLU2hvRmxLU0liYmtjOUtEbW43MlFUc2xSWlBFSGVvaDNsQmh4WS01eDdHUmEyQnVQLVVwc3V3Um4zSG9iMjAzQUZvdE9MOVE2dEl1cG5ieW9iTzJqMl9kS0Y2b0MwTENRdzlRaDE2OFY4eEJmRTM3bF9Gc2VEOWlSX05GdWZxWmpDSFQ4czJ2Tk8yZGdYVWYzU2xPbjAxM0d2YjcxOHhFX1pWT1Bqa0I3N3JKVmpYY2NJMlIwRFRCNjZuQWJXZ2JnWVFFbVdsS2VzSi1uT0pWcGZmY3A2ZC1DTDk0MXBB
config:
  RealEstate:environmentCode: dev
  RealEstate:regionCode: aue1
  RealEstate:regionName: Australia East
