name: Azure Boards reference check

on:
  # Triggers the workflow on pull request events to the "main" or "master" branch
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  azure-boards-reference-check:
    runs-on: ubuntu-latest

    steps:
      - name: ab-story-validation
        uses: emagers/ab-story-validation-action@v2.0.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    